name: Deploy JSON-RPC specification

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jsonrpc

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 15
        uses: actions/setup-node@v5
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Deploy to branch
        run: |
          git checkout -b assembled-spec
          git add -f openrpc.json
          git commit -m "assemble openrpc.json"
          git push -fu origin assembled-spec
